### ISSUE TITLE
read-me needed

### ISSUE THREAD

**Issue by nitrofurano** [ggnkua/bcx-basic-Jaguar#1]
It needs a read-me with instructions about how to use it on GNU/Linux! ;)

**Comment by ggnkua** [comment]
Care to write one? ;)

**Comment by ggnkua** [comment]
Jokes aside, like I told you on AtariAge, just install wine and run "wineconsole build.bat" - you should get instructions on how to build.

The only sticky subjects are

a) Virtualjaguar doesn't seem to run properly under wine - just use the linux version.
b) One person had troubles building stuff until he copied cmd.exe from Windows - this never happened in my setups - read the post here: http://atariage.com/forums/topic/258252-raptorbasic-for-linux/#entry3621642

Try that and let me know how it works for you. I suppose I could drop a small note about all this.

**Comment by ggnkua** [comment]
I added a linux guide on AtariAge - http://atariage.com/forums/topic/262800-setting-up-and-configuring-rb-from-scratch/#entry3707645
